services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "host"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
      - PORT=5055
    volumes:
      - ./config:/app/config
