services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: "jellyseerr"
    network_mode: host
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - ./config:/app/config
