services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /mnt/mediaStorage/data/shows:/mnt/mediaStorage/data/shows
      - /mnt/mediaStorage/data/anime/shows:/mnt/mediaStorage/data/anime/shows
      - /mnt/mediaStorage/downloads/complete/shows:/mnt/mediaStorage/downloads/complete/shows
      - /mnt/mediaStorage/downloads/complete/anime/shows:/mnt/mediaStorage/downloads/complete/anime/shows
    restart: unless-stopped