services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "host"
    env_file:
      - stack.env
    volumes:
      - ./config:/config
      - /mnt/mediaStorage/data/shows:/mnt/mediaStorage/data/shows
      - /mnt/mediaStorage/data/anime/shows:/mnt/mediaStorage/data/anime/shows
      - /mnt/mediaStorage/downloads/complete/shows:/mnt/mediaStorage/downloads/complete/shows
      - /mnt/mediaStorage/downloads/complete/anime/shows:/mnt/mediaStorage/downloads/complete/anime/shows
    restart: unless-stopped
