services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: "jellyfin"
    network_mode: host
    restart: unless-stopped
    env_file:
      - stack.env
        required: true
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_DIR_SHOWS}:${DATA_DIR_SHOWS}
      - ${DATA_DIR_ANIME-SHOWS}:${DATA_DIR_ANIME-SHOWS}
      - ${DATA_DIR_MOVIES}:${DATA_DIR_MOVIES}
      - ${DATA_DIR_ANIME-MOVIES}:${DATA_DIR_ANIME-MOVIES}
