services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: "sabnzbd"
    network_mode: host
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - ./config:/config
      - /mnt/mediaStorage/downloads:/mnt/mediaStorage/downloads
