services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /mnt/mediaStorage/downloads:/mnt/mediaStorage/downloads
    restart: unless-stopped
